modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "vanessamod"
version = "${file.jarVersion}"
displayName = "vanessamod"
logoFile = "vanessamod.png"
authors = "NessaVR"
description = '''
Vanessa's Mod, it does nothing but looks good!
'''

[[dependencies.vanessamod]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanessamod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"